import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#3525cd",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        tertiary: "#7e3000",
        "tertiary-container": "#a44100",
        "on-tertiary-container": "#ffd2be",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "#10B981",
        warning: "#F59E0B",
        border: "#E2E8F0",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        background: "#f7f9fb",
        surface: "#FFFFFF",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#464555",
        "text-primary": "#0F172A",
        "text-secondary": "#475569",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#c3c0ff",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["13px", "18px"],
        "body-md": ["14px", "20px"],
        "body-lg": ["16px", "24px"],
        "label-sm": ["11px", "14px"],
        "label-md": ["12px", "16px"],
        "headline-sm": ["18px", "26px"],
        "headline-md": ["24px", "32px"],
        "headline-lg": ["30px", "38px"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "panel-padding": "24px",
        "sidebar-width": "280px",
        "touch-target": "44px",
        "max-content-width": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
